appointment/urls.py
from django.conf.urls import url
from . import views
app_name = 'appointment'

urlpatterns = [
    url(r'^event/(?P<pk>[0-9]+)/update/$', views.UpdateEventDate.as_view(), name='updateevent'),
    url(r'^event/(?P<pk>[0-9]+)/update2/$', views.UpdateEventTime.as_view(), name='updateevent2'),
    url(r'^event/(?P<pk>[0-9]+)/update3/$', views.UpdateEventEndTime.as_view(), name='updateevent3'),
    url(r'^event/(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='eventdetail'),
    url(r'^eventnotification/(?P<pk>[0-9]+)/$', views.EventNotificationHandler.as_view(), name='eventnotificationhandler'),
    url(r'^makeappointment/step0/$', views.MakeAppointmentChooseDoctor.as_view(), name='makeappointmentchoosedoctor'),
    url(r'^makeappointment/step1/$', views.MakeAppointmentDate.as_view(), name='makeappointmentdate'),
    url(r'^makeappointment/step1/doctor/$', views.MakeAppointmentDateDoctor.as_view(), name='doctormakeappointmentdate'),
    url(r'^makeappointment/step2/$', views.MakeAppointmentTime.as_view(), name='makeappointmenttime'),
    url(r'^makeappointment/step3/$', views.MakeAppointmentEndTime.as_view(), name='makeappointmentendtime'),
    url(r'^calendarappointment/$', views.MakeCalendarAppointment.as_view(), name='calendarappointment'),
]

doctor_homepage/urls.py
from django.conf.urls import url
from doctor_homepage import views

app_name = 'doctor'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^event/(?P<pk>[0-9]+)/delete$', views.DeleteEvent.as_view(), name='deleteevent'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),

]

h_admin_homepage/urls.py
from django.conf.urls import url
from h_admin_homepage import views

app_name = 'h_admin'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
    url(r'^register-staff/$', views.CreateUserFormView.as_view(), name='addstaff'),
    url(r'^register-staff/add-doctor-step1/$', views.CreateDoctorFormView.as_view(), name='register_doctor1'),
    url(r'^register-staff/add-doctor-step2/$', views.CreateDoctor2FormView.as_view(), name='register_doctor2'),
    url(r'^register-staff/add-nurse-step1/$', views.CreateNurseFormView.as_view(), name='register_nurse'),
    url(r'^register-staff/add-nurse-step2/$', views.CreateNurse2FormView.as_view(), name='register_nurse2'),
    url(r'^register-staff/add-hospital-admin/$', views.CreateAdminFormView.as_view(), name='register_admin'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),
    url(r'^statistics/$', views.StatsView.as_view(), name='statistics'),
    url(r'^upload-csv-file/$', views.UploadCsvFile.as_view(), name='upload_csv_file'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.DeleteEvent.as_view(), name='deleteevent'),
]

healthnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from healthnet import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage_redirect, name='homepage_redirect'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^h_admin_homepage/', include('h_admin_homepage.urls')),
    url(r'^doctor_homepage/', include('doctor_homepage.urls')),
    url(r'^patient_homepage/', include('patient_homepage.urls')),
    url(r'^nurse_homepage/', include('nurse_homepage.urls')),
    url(r'^prescriptions/', include('prescription.urls')),
    url(r'^appointments/', include('appointment.urls')),
    url(r'^test_results/', include('test_result.urls')),
    url(r'^message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [
    url(r'^inbox/$', views.InboxView.as_view(), name='inbox'),
    url(r'^outbox/$', views.OutboxView.as_view(), name='outbox'),
    url(r'^deleted/$', views.DeletedView.as_view(), name='deleted'),
    url(r'^new_message/$', views.MessageFormView.as_view(), name='newmessage'),
    url(r'^message/(?P<pk>[0-9]+)/$', views.MessageDetailView.as_view(), name='detail'),
    url(r'^remove/(?P<pk>[0-9]+)/$', views.RemoveMessageView.as_view(), name='remove'),
    url(r'^restore/(?P<pk>[0-9]+)/$', views.RestoreMessageView.as_view(), name='restore'),

]

nurse_homepage/urls.py
from django.conf.urls import url
from nurse_homepage import views

app_name = 'nurse'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
]

patient_homepage/urls.py
from django.conf.urls import url
from patient_homepage import views

app_name = 'patient'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emr/$', views.viewemr, name='emr'),
    url(r'^emr/chronological/$', views.EMRChronView.as_view(), name='chronemr'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update1'),
    url(r'^profile/(?P<pk>[0-9]+)/update2/$', views.UpdatePatientInfo.as_view(), name='update2'),
    url(r'^addextrainfo/$', views.ExtraInfoFormView.as_view(), name='extra'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.DeleteEvent.as_view(), name='deleteevent'),
]

appointment/views.py
from django.shortcuts import render
from django.views.generic import View, DetailView
from django.http import HttpResponseRedirect
from log.models import *
from .forms import *
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone


class EventDetail(DetailView):
    model = Event
    template = 'appointment/event_detail.html'


class MakeAppointmentChooseDoctor(View):
    form_class = EventFormChooseDoctor
    template_name = 'appointment/makeappointmentchoosedoctor.html'

    def get(self, request):
        initial = {'doctor': request.session.get('doctor', None)}
        form = self.form_class(user=request.user, initial=initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        initial = {'doctor': request.session.get('doctor', None)}
        form = self.form_class(request.POST, user=request.user, initial=initial)
        if form.is_valid():
            request.session['doctor'] = form.cleaned_data['doctor'].pk
            return HttpResponseRedirect(reverse('appointment:makeappointmentdate'))
        return render(request, self.template_name, {'form': form})


class MakeAppointmentDateDoctor(View):
    template_name = 'appointment/makeappointmentdate.html'
    form_class = EventFormDateStaff

    def get(self, request):
        initial = {'name': request.session.get('name', None),
                   'patient': request.session.get('patient', None),
                   }
        if request.session.get('date') is not None:
            initial['date'] = request.session.get('date', None)
        else:
            initial['date'] = timezone.now()

        form = self.form_class(user=request.user, userpk=request.user.pk, initial=initial)
        request.session['doctor'] = request.user.pk
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        initial = {'name': request.session.get('name', None),
                   'patient': request.session.get('patient', None),
                   'date': request.session.get('date', None),
                   }
        form = self.form_class(request.POST, user=request.user, userpk=request.session['doctor'], initial=initial)
        if form.is_valid():
            request.session['name'] = form.cleaned_data['name']
            request.session['date'] = form.cleaned_data['date'].isoformat()
            if form.cleaned_data['patient']:
                request.session['patient'] = form.cleaned_data['patient'].pk
            else:
                request.session['patient'] = None
            return HttpResponseRedirect(reverse('appointment:makeappointmenttime'))
        return render(request, self.template_name, {'form': form})


class MakeAppointmentDate(View):
    template_name = 'appointment/makeappointmentdate.html'

    def get(self, request):

        if Nurse.objects.filter(pk=request.user.pk).exists() or H_Admin.objects.filter(pk=request.user.pk).exists():
            initial = {'name': request.session.get('name', None),
                       'patient': request.session.get('patient', None),
                       }
            if request.session.get('date') is not None:
                initial['date'] = request.session.get('date', None)
            else:
                initial['date'] = timezone.now()
            form_class = EventFormDateStaff
            form = form_class(user=request.user, userpk=request.session['doctor'], initial=initial)

        elif Patient.objects.filter(pk=request.user.pk).exists():
            initial = {'name': request.session.get('name', None) }
            if request.session.get('date') is not None:
                initial['date'] = request.session.get('date', None)
            else:
                initial['date'] = timezone.now()
            form_class = EventFormDatePatient
            form = form_class(None, initial=initial)
            request.session['doctor'] = request.user.patient.doctor.pk

        else:  # Doctor
            initial = {'name': request.session.get('name', None),
                       'patient': request.session.get('patient', None),
                       }
            if request.session.get('date') is not None:
                initial['date'] = request.session.get('date', None)
            else:
                initial['date'] = timezone.now()
            form_class = EventFormDateStaff
            form = form_class(user=request.user, userpk=request.user.pk, initial=initial)
            request.session['doctor'] = request.user.pk
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if hasattr(request.user, 'patient'):
            initial = {'name': request.session.get('name', None),
                       'date': request.session.get('date', None),
                       }
            form_class = EventFormDatePatient
            form = form_class(request.POST, initial=initial)
        else:
            initial = {'name': request.session.get('name', None),
                       'patient': request.session.get('patient', None),
                       'date': request.session.get('date', None),
                       }
            form_class = EventFormDateStaff
            form = form_class(request.POST, user=request.user, userpk=request.session['doctor'], initial=initial)
        if form.is_valid():
            request.session['name'] = form.cleaned_data['name']
            request.session['date'] = form.cleaned_data['date'].isoformat()
            if not hasattr(request.user, 'patient'):
                if form.cleaned_data['patient']:
                    request.session['patient'] = form.cleaned_data['patient'].pk
                else:
                    request.session['patient'] = None
            return HttpResponseRedirect(reverse('appointment:makeappointmenttime'))
        return render(request, self.template_name, {'form': form})


class MakeAppointmentTime(View):
    form_class = EventFormTime
    template_name = 'appointment/makeappointmenttime.html'

    def get(self, request):
        initial = {'start_time': request.session.get('start_time', None)}
        form = self.form_class(user=Doctor.objects.get(pk=request.session['doctor']), day=request.session['date'], initial=initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if request.user.is_staff:
            initial = {'start_time': request.session.get('start_time', None)}
            form = self.form_class(request.POST, user=None, day=None, initial=initial)
            if form.is_valid():
                request.session['start_time'] = form.cleaned_data['start_time'].isoformat()
                return HttpResponseRedirect(reverse('appointment:makeappointmentendtime'))
        else:
            form = self.form_class(request.POST, user=None, day=None)
            if form.is_valid():
                patient = request.user.patient
                doctor = patient.doctor
                name = request.session['name']
                date = request.session['date']
                start_time = form.cleaned_data['start_time']
                end_time = (datetime.datetime(2000, 1, 1, hour=start_time.hour, minute=start_time.minute,
                                              second=start_time.second) + datetime.timedelta(minutes=30)).time()
                event = Event.objects.create(patient=patient,
                                             doctor=doctor,
                                             name=name,
                                             date=date,
                                             start_time=start_time,
                                             end_time=end_time)
                log = Log.objects.create(
                    date_time=timezone.now(),
                    actor=request.user,
                    subject=patient.user,
                    hospital=patient.hospital,
                    type='create',
                    description='Appointment for Doctor: ' + doctor.user.get_full_name() + ' and Patient: ' +
                                patient.user.get_full_name() + ' created for: ' + date + ' at: ' + start_time.strftime('%I:%M %p'),
                )
                EventLog.objects.create(
                    log=log,
                    patient=patient,
                    doctor=doctor,
                    eventtime=start_time,
                    eventdate=date
                )
                return HttpResponseRedirect(reverse('patient:index'))
        return render(request, self.template_name, {'form': form})


class MakeAppointmentEndTime(View):
    form_class = EventFormEndTime
    template_name = 'appointment/makeappointmentendtime.html'

    def get(self, request):
        form = self.form_class(user=Doctor.objects.get(pk=request.session['doctor']),
                               day=request.session['date'],
                               start_time=request.session['start_time'])
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, user=None, day=None, start_time=None)
        if form.is_valid():
            if request.session['patient']:
                patient = Patient.objects.get(pk=request.session['patient'])
                hospital = patient.hospital
            else:
                patient = None
            if hasattr(request.user, 'nurse') or hasattr(request.user, 'h_admin'):
                doctor = Doctor.objects.get(pk=request.session['doctor'])
                if hasattr(request.user, 'nurse'):
                    hospital = request.user.nurse.hospital
                else:
                    hospital = request.user.h_admin.hospital
            else:
                doctor = request.user.doctor
                hospital = None
            name = request.session['name']
            date = request.session['date']

appointment/templates/appointment/event_detail.html
{% extends 'accounts/base.html' %}

{% block title %} {{ event.name }} {% endblock %}

{% block body %}
    <div class="container">
    {% if error_message %}
        <p style="color:red"><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% if request.user.patient%}
        <h2> &nbsp; Your Appointment Information:</h2>
    {% elif request.user.doctor %}
        {% if event.patient.user.get_full_name != '' and event.patient %}
            <h2> &nbsp; {{ event.patient.user.get_full_name }}'s Appointment Information:</h2>
        {% else %}
            <h2> &nbsp; Event Information:</h2>
        {% endif %}
    {% elif request.user.nurse or request.user.h_admin %}
        <h2> &nbsp; {{ event.patient.user.get_full_name }}'s Appointment Information:</h2>
    {% endif %}
    <!-- Appointment Information -->
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Appointment Information</h4>
        </div>

        <div class="panel-body">
            <ul>
                <li> Name: {{ event.name }}</li>
                <li> Date: {{ event.date }}</li>
                <li> Start time: {{ event.start_time }}</li>
                <li> End time: {{ event.end_time }}</li>
            </ul>
    <div class="col-md-12" style="text-align:right">
            {% if request.user.nurse.hospital == event.patient.hospital or request.user.h_admin.hospital == event.patient.hospital or request.user.doctor or request.user.patient == event.patient %}
                {% if request.user.patient or request.user.doctor or request.user.h_admin %}
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#popUpWindow">Cancel Appointment</button>

                <div class="modal fade" id="popUpWindow" style="text-align:left">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <div class="modal-header">

                                <h3>Cancel Appointment</h3>
                            </div>

                            <div class="modal-body">
                                Are you sure you want to cancel this appointment?
                            </div>

                            <div class="modal-footer">
                                {% if request.user.patient%}
                                    <a href="{% url 'patient:deleteevent' event.pk %}">
                                {% elif request.user.doctor%}
                                    <a href="{% url 'doctor:deleteevent' event.pk %}">
                                {% elif request.user.h_admin %}
                                    <a href="{% url 'h_admin:deleteevent' event.pk %}">
                                {% endif %}
                                <button type="submit" class="btn btn-danger">Cancel Appointment</button>
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Back</button>
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
                {% endif %}

                <a href="{% url 'appointment:updateevent' event.pk%}">
                    <button type="submit" class="btn btn-success">Update Appointment</button>
                </a>
            {% endif %}
    </div>
        </div>

    </div>



{#    {% if request.user.nurse.hospital == event.patient.hospital or request.user.h_admin.hospital == event.patient.hospital or request.user.doctor or request.user.patient == event.patient %}#}
{#    <!-- Cancel Appointment -->#}
{#    <div class="container">#}
{#        <a href="{% url 'appointment:updateevent' event.pk%}">#}
{##}
{#                    <div class="col-md-3 text-left">#}
{#                        <button type="submit" class="btn btn-success">Update Appointment</button>#}
{#                    </div>#}
{##}
{#        </a>#}
{#        {% if request.user.patient or request.user.doctor or request.user.h_admin %}#}
{#            <div class="col-md-3">#}
{#                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#popUpWindow">Cancel Appointment</button>#}
{#            </div>#}
{##}
{#        <div class="modal fade" id="popUpWindow">#}
{#            <div class="modal-dialog">#}
{#                <div class="modal-content">#}
{##}
{#                    <div class="modal-header">#}
{##}
{#                        <h3>Cancel Appointment</h3>#}
{#                    </div>#}
{##}
{#                    <div class="modal-body">#}
{#                        Are you sure you want to cancel this appointment?#}
{#                    </div>#}
{##}
{#                    <div class="modal-footer">#}
{#                        {% if request.user.patient%}#}
{#                            <a href="{% url 'patient:deleteevent' event.pk %}">#}
{#                        {% elif request.user.doctor%}#}
{#                            <a href="{% url 'doctor:deleteevent' event.pk %}">#}
{#                        {% elif request.user.h_admin %}#}
{#                            <a href="{% url 'h_admin:deleteevent' event.pk %}">#}
{#                        {% endif %}#}
{#                        <button type="submit" class="btn btn-danger">Cancel Appointment</button>#}
{#                        <button type="button" class="btn btn-primary" data-dismiss="modal">Back</button>#}
{#                        </a>#}
{#                    </div>#}
{##}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        {% endif %}#}
{##}
{#    </div>#}
{#            {% endif %}#}
    </div>

{% endblock %}

appointment/templates/appointment/makeappointmentdate.html
{% extends 'accounts/base.html' %}
{% block title %} Make Appointment {% endblock %}
{% block body %}
<div class="center">
    {% if request.user.patient or request.user.doctor %}
        <h3>Create Appointment</h3>
    {% else %}
        <h3>Create Appointment (Continued)</h3>
    {% endif %}
</div>
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-6 center-block " style="float:none;">
            <div class="panel panel panel-default">
                <div class="panel-body">

                    {% if error_message %}
                        <div class="col-sm-offset-4 col-sm-8">
                            <p style="color:red"><strong>{{ error_message }}</strong></p>
                        </div>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% include 'accounts/form_template.html' %}
                        <div class="form-group">
                            <div class="col-md-6" style="text-align:left">
                                {% if request.user.patient %}
                                    <a href="{% url 'patient:index' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                {% elif request.user.doctor %}
                                    <a href="{% url 'doctor:index' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                {% else %}
                                    <a href="{% url 'appointment:makeappointmentchoosedoctor' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                {% endif %}
                            </div>
                                <div class="col-md-6" style="text-align:right">
                                {% if request.user.patient %}
                                    <a href="{% url 'patient:index' %}">
                                {% elif request.user.doctor %}
                                    <a href="{% url 'doctor:index' %}">
                                {% elif request.user.nurse %}
                                    <a href="{% url 'nurse:index' %}">
                                {% elif request.user.h_admin %}
                                    <a href="{% url 'h_admin:index' %}">
                                {% endif %}
                                        <button type="button" class="btn btn-danger">Cancel</button>
                                    </a>

                                <button type="submit" class="btn btn-success">Continue</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

appointment/templates/appointment/updateappointmentdate.html
{% extends 'accounts/base.html' %}
{% block title %} Update Appointment {% endblock %}
{% block body %}

<body>
<div class="center"><h3>Update Appointment</h3></div>
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-6 center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                    <a href="{% url 'appointment:eventdetail' pk %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>
                                <div class="col-md-6" style="text-align:right">
                                    {% if request.user.patient %}
                                        <a href="{% url 'patient:index' %}">
                                    {% elif request.user.doctor %}
                                        <a href="{% url 'doctor:index' %}">
                                    {% elif request.user.nurse %}
                                        <a href="{% url 'nurse:index' %}">
                                    {% elif request.user.h_admin %}
                                        <a href="{% url 'h_admin:index' %}">
                                    {% endif %}
                                            <button type="button" class="btn btn-danger">Cancel</button>
                                    </a>
                                    <button type="submit" class="btn btn-success">Choose time</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</body>

{% endblock %}

appointment/templates/appointment/updateappointmentendtime.html
{% extends 'accounts/base.html' %}
{% block title %} Update Appointment {% endblock %}
{% block body %}

<body>
<div class="center"><h3>Update Appointment(continue)</h3></div>
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-5  center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                    <a href="{% url 'appointment:updateevent2' pk %}">
                                            <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>
                                <div class="col-md-6" style="text-align:right">
                                {% if request.user.patient %}
                                    <a href="{% url 'patient:index' %}">
                                {% elif request.user.doctor %}
                                    <a href="{% url 'doctor:index' %}">
                                {% elif request.user.nurse %}
                                    <a href="{% url 'nurse:index' %}">
                                {% elif request.user.h_admin %}
                                    <a href="{% url 'h_admin:index' %}">
                                {% endif %}
                                        <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                                <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</body>

{% endblock %}