accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.PatientFormView.as_view(), name='register'),
    url(r'^register/step2/$', views.BasicInfo.as_view(), name='register2'),
    url(r'^admitpatient/$', views.AdmissionView.as_view(), name='admit'),
    url(r'^admitpatient/doctor$', views.AdmissionViewDoctor.as_view(), name='admitdoc'),
    url(r'^dischargepatient/$', views.DischargeView.as_view(), name='discharge'),
    url(r'^updatepassword/$', views.PasswordUpdateView.as_view(), name='updatepassword'),
    url(r'^transferpatient/$', views.TransferPatientView.as_view(), name='transfer'),
    url(r'^getdoctors/$', views.AjaxGetDoctorsView.as_view(), name='ajax_get_doctors'),
    url(r'^receivepatient/(?P<pk>[0-9]+)/$', views.ReceivePatientView.as_view(), name='transfernotificationhandler'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.patient_profile, name='patientprofile'),
    url(r'^updatemedicalinfo/(?P<pk>[0-9]+)/$', views.UpdateMedicalFormView.as_view(), name='updatemedicalinfo'),
    url(r'^help/$', views.HelpView.as_view(), name='help'),
    url(r'^locations/$', views.LocationsView.as_view(), name='locations'),
]

appointment/urls.py
from django.conf.urls import url
from . import views
app_name = 'appointment'

urlpatterns = [
    url(r'^event/(?P<pk>[0-9]+)/update/$', views.UpdateEventDate.as_view(), name='updateevent'),
    url(r'^event/(?P<pk>[0-9]+)/update2/$', views.UpdateEventTime.as_view(), name='updateevent2'),
    url(r'^event/(?P<pk>[0-9]+)/update3/$', views.UpdateEventEndTime.as_view(), name='updateevent3'),
    url(r'^event/(?P<pk>[0-9]+)/$', views.EventDetail.as_view(), name='eventdetail'),
    url(r'^eventnotification/(?P<pk>[0-9]+)/$', views.EventNotificationHandler.as_view(), name='eventnotificationhandler'),
    url(r'^makeappointment/step0/$', views.MakeAppointmentChooseDoctor.as_view(), name='makeappointmentchoosedoctor'),
    url(r'^makeappointment/step1/$', views.MakeAppointmentDate.as_view(), name='makeappointmentdate'),
    url(r'^makeappointment/step1/doctor/$', views.MakeAppointmentDateDoctor.as_view(), name='doctormakeappointmentdate'),
    url(r'^makeappointment/step2/$', views.MakeAppointmentTime.as_view(), name='makeappointmenttime'),
    url(r'^makeappointment/step3/$', views.MakeAppointmentEndTime.as_view(), name='makeappointmentendtime'),
    url(r'^calendarappointment/$', views.MakeCalendarAppointment.as_view(), name='calendarappointment'),
]

healthnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from healthnet import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage_redirect, name='homepage_redirect'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^h_admin_homepage/', include('h_admin_homepage.urls')),
    url(r'^doctor_homepage/', include('doctor_homepage.urls')),
    url(r'^patient_homepage/', include('patient_homepage.urls')),
    url(r'^nurse_homepage/', include('nurse_homepage.urls')),
    url(r'^prescriptions/', include('prescription.urls')),
    url(r'^appointments/', include('appointment.urls')),
    url(r'^test_results/', include('test_result.urls')),
    url(r'^message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [
    url(r'^inbox/$', views.InboxView.as_view(), name='inbox'),
    url(r'^outbox/$', views.OutboxView.as_view(), name='outbox'),
    url(r'^deleted/$', views.DeletedView.as_view(), name='deleted'),
    url(r'^new_message/$', views.MessageFormView.as_view(), name='newmessage'),
    url(r'^message/(?P<pk>[0-9]+)/$', views.MessageDetailView.as_view(), name='detail'),
    url(r'^remove/(?P<pk>[0-9]+)/$', views.RemoveMessageView.as_view(), name='remove'),
    url(r'^restore/(?P<pk>[0-9]+)/$', views.RestoreMessageView.as_view(), name='restore'),

]

nurse_homepage/urls.py
from django.conf.urls import url
from nurse_homepage import views

app_name = 'nurse'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
]

prescription/urls.py
from django.conf.urls import url
from . import views

app_name = 'prescription'

urlpatterns = [
    url(r'^addprescription/(?P<pk>[0-9]+)/$', views.CreatePrescriptionView.as_view(), name='add'),
    url(r'^removeprescription/(?P<pk>[0-9]+)/$', views.RemovePrescriptionView.as_view(), name='remove'),
    url(r'^notificationhandler/(?P<pk>[0-9]+)/$', views.PrescriptionNotificationHandler.as_view(), name='notificationhandler'),
]

test_result/urls.py
from django.conf.urls import url
from test_result import views

app_name = 'test_result'

urlpatterns = [
    url(r'^addtestresult/(?P<pk>[0-9]+)/$', views.CreateTestResultView.as_view(), name='add'),
    url(r'^testfile/(?P<pk>[0-9]+)/$', views.FileView.as_view(), name='file'),
    url(r'^testfile/log/(?P<pk>[0-9]+)/$', views.LogFileView.as_view(), name='logfile'),
    url(r'^testresulthandler/(?P<pk>[0-9]+)/$', views.TestResultNotificationHandler.as_view(), name='notificationhandler'),
    url(r'^approvetestresulthandler/(?P<pk>[0-9]+)/$', views.ApproveTestResultNotificationHandler.as_view(), name='approvenotificationhandler'),
    url(r'^cancelapprovetestresult/(?P<pk>[0-9]+)/$', views.CancelApproveTestResultNotificationHandler.as_view(), name='cancelapprovetest'),
    url(r'^approvetestresult/(?P<pk>[0-9]+)/$', views.ApproveTestResult.as_view(), name='approvetestresult'),

]

accounts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.core.validators import RegexValidator


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('Staff Status'), default=False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    # avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def get_message_count(self):
        count = 0
        for message in self.receiver.all():
            if not message.deleted:
                count += 1
        return count

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.get_full_name() + " (" + self.email + ")"


class Hospital(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=16)  # validators should be a list

    def formatted_phone(self):
        return "%s%s%s-%s%s%s-%s%s%s%s" % tuple(self.phone_number)

    def __str__(self):
        return self.name


class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospital = models.ForeignKey(Hospital)

    def __str__(self):
        return "Nurse " + self.user.get_full_name() + " (" + self.user.email + ")"

    def get_doctors(self):
        return self.doctor_set.all()


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospitals = models.ManyToManyField(Hospital)
    max_patients = models.IntegerField()
    nurses = models.ManyToManyField(Nurse)

    def __str__(self):
        return "Dr. " + self.user.get_full_name() + " (" + self.user.email + ")"

    def get_hospitals(self):
        return self.hospitals.all()

    def get_nurses(self):
        return self.nurses.all()


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    insurance_number = models.CharField(max_length=13)
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    height = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    blood_type = models.CharField(max_length=10, blank=True)
    hospital = models.ForeignKey(Hospital)
    doctor = models.ForeignKey(Doctor)
    isInHospital = models.BooleanField(default=False)
    isInTransit = models.BooleanField(default=False)
    emergency_first_name = models.CharField(max_length=30, blank=True)
    emergency_last_name = models.CharField(max_length=30, blank=True)
    emergency_phone_number = models.CharField(blank=True, max_length=16)
    emergency_address = models.CharField(max_length=200, blank=True)
    emergency_relationship = models.CharField(max_length=50, blank=True)

    def get_absolute_url(self):
        return reverse('patient:profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.user.get_full_name() + " (" + self.user.email + ")"

    def get_filtered_events(self):
        return self.event_set.order_by('date').reverse()

    def no_basic_info(self):
        no = (not self.emergency_first_name) or (not self.phone_number) or (not self.address) \
             or (not self.emergency_last_name) or (not self.emergency_address) \
             or (not self.emergency_phone_number) or (not self.emergency_relationship)
        return no

    def get_unapproved_tests_number(self):
        all_tests = self.testresult_set.all()
        ans = 0
        for test in all_tests:
            if test.is_released:
                ans += 1
        return ans


class H_Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospital = models.ForeignKey(Hospital)

    def __str__(self):
        return "Admin " + self.user.get_full_name() + " (" + self.user.email + ")"


class Notification(models.Model):
    name = models.CharField(max_length=100, blank=False)
    recipient = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    is_seen = models.BooleanField(default=False, blank=False)


class AppointmentNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    appointment = models.IntegerField()


class PrescriptionNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class RemovedPrescriptionNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class TestResultNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class ApproveTestResultNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    test_result = models.IntegerField()


class ReceiveTransferNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    transfer = models.IntegerField()


class HospitalStay(models.Model):
    REASON_CHOICES = (
        ('Infectious Disease', 'Infectious Disease'),
        ('Traumatic Injury', 'Traumatic Injury'),
        ('Poisoning/Drugs', 'Poisoning/Drugs'),
        ('Cardiac Issues', 'Cardiac Issues'),
        ('Chronic Illness', 'Chronic Illness'),
        ('Surgery', 'Surgery'),
        ('Other', 'Other'),
    )

    patient = models.ForeignKey(Patient)
    hospital = models.ForeignKey(Hospital)
    admission_date = models.DateField()
    discharge_date = models.DateField(blank=True, null=True)
    reason = models.CharField(max_length=50, choices=REASON_CHOICES)
    admission_details = models.CharField(blank=True, max_length=256)
    discharge_details = models.CharField(blank=True, max_length=256)
    admit_employee = models.ForeignKey(User, related_name='admit_employee')
    discharge_employee = models.ForeignKey(User, related_name='discharge_employee', blank=True, null=True)

    def __str__(self):
        return self.patient.user.first_name + " " + self.patient.user.last_name +\
               " was admitted to " + self.hospital.name + " for: " + self.reason


class OngoingTransfer(models.Model):
    patient = models.ForeignKey(Patient)
    dest_doctor = models.ForeignKey(Doctor, related_name='dest_doctor')
    dest_hospital = models.ForeignKey(Hospital, related_name='dest_hospital')
    src_doctor = models.ForeignKey(Doctor, related_name='src_doctor')
    src_hospital = models.ForeignKey(Hospital, related_name='src_hospital')

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="/static/favicon.ico"/>
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class = "glyphicon glyphicon-menu-hamburger"></span>
                </button>
                <a class="navbar-brand" href="#" style="font-family: 'Open Sans', sans-serif;font-size: 14pt">HealthNet</a>
            </div>

            <!-- NavBar Items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% if request.session.dash%}active{% endif %}">
                        {% if request.user.patient %}
                            <a href="{% url 'patient:index' %}">
                        {% elif request.user.doctor %}
                            <a href="{% url 'doctor:index' %}">
                        {% elif request.user.nurse %}
                            <a href="{% url 'nurse:index' %}">
                        {% elif request.user.h_admin %}
                            <a href="{% url 'h_admin:index' %}">
                        {% endif %}
                                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Dashboard
                            </a>
                    </li>
                    <!-- EMR -->
                    <li class="{% if request.session.emr %}active{% endif %}">
                        {% if request.user.patient %}
                            <a href="{% url 'patient:emr' %}">
                                <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp; EMR
                            </a>
                        {% elif request.user.doctor %}
                        <a href="{% url 'doctor:emr' %}">
                                <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Patient List
                            </a>
                        {% elif request.user.nurse %}
                            <a href="{% url 'nurse:emr' %}">
                                <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Patient List
                            </a>
                        {% else %}
                            <a href="{% url 'h_admin:emr' %}">
                                <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Patient List
                            </a>
                        {% endif %}
                    </li>

                    <!-- Messages -->
                    {% if not request.user.patient %}
                        <li class="{% if request.session.messages %}active{% endif %}">
                            <a href="{% url 'message:inbox' %}">
                                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp; Messages
                                <span class="badge">{{ request.user.get_message_count }} </span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- Notifications -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>&nbsp; Notifications <span class="badge">{{ request.user.notification_set.count }}</span> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% for notification in request.user.notification_set.all %}
                                {% if not notification.is_seen %}
                                    {% if notification.appointmentnotification %}
                                        <li> <a href="{% url 'appointment:eventnotificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% elif notification.prescriptionnotification  %}
                                        <li> <a href="{% url 'prescription:notificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% elif notification.removedprescriptionnotification  %}
                                        <li> <a href="{% url 'prescription:notificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% elif notification.testresultnotification  %}
                                        <li> <a href="{% url 'test_result:notificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% elif notification.approvetestresultnotification  %}
                                        <li> <a href="{% url 'test_result:approvenotificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% elif notification.receivetransfernotification  %}
                                        <li> <a href="{% url 'accounts:transfernotificationhandler' pk=notification.pk %}" >{{ notification.name }}</a></li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                    <!-- Profile -->
                    <li class="{% if request.session.profile %}active{% endif %}">
                        {% if request.user.patient %}
                            <a href="{% url 'accounts:patientprofile' request.user.pk%}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profile
                            </a>
                        {% elif request.user.doctor %}
                            <a href="{% url 'doctor:profile' request.user.pk %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profile
                            </a>
                        {% elif request.user.nurse %}
                            <a href="{% url 'nurse:profile' request.user.pk %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profile
                            </a>
                        {% elif request.user.h_admin %}
                            <a href="{% url 'h_admin:profile' request.user.pk %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profile
                            </a>
                        {% endif %}
                    </li>
                    <li class="">
                        <a href="{% url 'accounts:help'%}">
                            <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Help
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'accounts:logout'%}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Log Out
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>


accounts/templates/accounts/form_template.html
{% for field in form %}
    <div class = "form-group">
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-8" style="padding-top: 5px">{{ field }}</div>
        <div class="col-sm-offset-4 col-sm-8">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <div class="col-sm-offset-4 col-sm-8">
            <span id="helpText" class="help-block form-text text-muted">{{ field.help_text }}</span>
        </div>
    </div>
{% endfor %}

accounts/templates/accounts/homepage.html
{% extends 'accounts/landing_base.html' %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

{% block title %} Welcome {% endblock %}
{% block body %}
<script>
    var i = 0;
    $(document).ready(function() {
        document.getElementById('image').src = "/static/images/image3.jpg";
        setTimer();
    });

    function setTimer() {
        setInterval('changeImage()', 7000);
    }

    function changeImage() {
        i++;
        if (i == 5) i = 1;

        $(document.getElementById('image')).fadeOut(500, 'linear', function() {
            document.getElementById('image').src = "static/images/image" + i + ".jpg";
            $(document.getElementById('image')).fadeIn(500, 'linear');
        });
    }
</script>

<div class="center">
    <h1>HealthNet</h1>
    <p>
        <div id="slideshow" style="width:562px; margin:0 auto;">
                    <img src="" id="image">
        </div>
    <br>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:register' %}">Register</a>
</div>

{% endblock %}

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/transferpatient.html
{% extends 'accounts/base.html' %}
{% block title %} Transfer Patient {% endblock %}
{% block body %}

<script type="text/javascript" language="javascript">
    $(document).ready(function() {

    $("#id_hospital").change( function(){

        $.ajax({
            url: "{% url 'accounts:ajax_get_doctors' %}",
            type: 'GET',
            data:  {hospital: $("#id_hospital").val()},
            dataType: "json",
            success: function(resp){
                $("#id_doctor").empty();
                $.each(resp, function(idx, obj) {
                    $("#id_doctor").append($('<option></option>').attr('value', obj.pk).text(obj.fields.first_name + ' ' + obj.fields.last_name + ' (' + obj.fields.email + ')'));
                });
            },
            error: function(jqXHR, textStatus, errorThrown) {
                alert(errorThrown);
            }
        });

    });
});
</script>

<body>
    <div class="center"><h3>Transfer a Patient</h3></div>
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-6 center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                {% if request.user.doctor %}
                                    <a href="{% url 'doctor:index' %}">
                                {% elif request.user.nurse %}
                                    <a href="{% url 'nurse:index' %}">
                                {% elif request.user.h_admin %}
                                    <a href="{% url 'h_admin:index' %}">
                                {% endif %}
                                    <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>
                                <div class="col-md-6" style="text-align:right">
                                {% if request.user.doctor %}
                                    <a href="{% url 'doctor:index' %}">
                                {% elif request.user.h_admin %}
                                    <a href="{% url 'h_admin:index' %}">
                                {% endif %}
                                    <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                                <button type="submit" class="btn btn-success">Transfer Patient</button>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
</body>

{% endblock %}

accounts/templates/accounts/user_update_form.html
{% extends 'accounts/base.html' %}
{% block title %}Update Profile{% endblock %}
{% block body %}
    <div class="center"><h3>Update Profile Information</h3></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6  center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">

                                <div class="col-md-6" style="text-align:left">
                                    {% if request.user.patient %}
                                        <a href="{% url 'accounts:patientprofile' request.user.pk %}">
                                    {% elif request.user.doctor %}
                                        <a href="{% url 'doctor:profile' request.user.pk %}">
                                    {% elif request.user.nurse %}
                                        <a href="{% url 'nurse:profile' request.user.pk %}">
                                    {% elif request.user.h_admin %}
                                        <a href="{% url 'h_admin:profile' request.user.pk %}">
                                    {% endif %}
                                            <button type="button" class="btn btn-primary">Go Back</button>
                                        </a>
                                </div>
                                <div class="col-md-6" style="text-align:right">
                                    {% if request.user.patient %}
                                        <a href="{% url 'accounts:patientprofile' request.user.pk %}">
                                    {% elif request.user.doctor %}
                                        <a href="{% url 'doctor:profile' request.user.pk %}">
                                    {% elif request.user.nurse %}
                                        <a href="{% url 'nurse:profile' request.user.pk %}">
                                    {% elif request.user.h_admin %}
                                        <a href="{% url 'h_admin:profile' request.user.pk %}">
                                    {% endif %}
                                            <button type="button" class="btn btn-danger">Cancel</button>
                                        </a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}