accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.PatientFormView.as_view(), name='register'),
    url(r'^register/step2/$', views.BasicInfo.as_view(), name='register2'),
    url(r'^admitpatient/$', views.AdmissionView.as_view(), name='admit'),
    url(r'^admitpatient/doctor$', views.AdmissionViewDoctor.as_view(), name='admitdoc'),
    url(r'^dischargepatient/$', views.DischargeView.as_view(), name='discharge'),
    url(r'^updatepassword/$', views.PasswordUpdateView.as_view(), name='updatepassword'),
    url(r'^transferpatient/$', views.TransferPatientView.as_view(), name='transfer'),
    url(r'^getdoctors/$', views.AjaxGetDoctorsView.as_view(), name='ajax_get_doctors'),
    url(r'^receivepatient/(?P<pk>[0-9]+)/$', views.ReceivePatientView.as_view(), name='transfernotificationhandler'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.patient_profile, name='patientprofile'),
    url(r'^updatemedicalinfo/(?P<pk>[0-9]+)/$', views.UpdateMedicalFormView.as_view(), name='updatemedicalinfo'),
    url(r'^help/$', views.HelpView.as_view(), name='help'),
    url(r'^locations/$', views.LocationsView.as_view(), name='locations'),
]

healthnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from healthnet import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage_redirect, name='homepage_redirect'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^h_admin_homepage/', include('h_admin_homepage.urls')),
    url(r'^doctor_homepage/', include('doctor_homepage.urls')),
    url(r'^patient_homepage/', include('patient_homepage.urls')),
    url(r'^nurse_homepage/', include('nurse_homepage.urls')),
    url(r'^prescriptions/', include('prescription.urls')),
    url(r'^appointments/', include('appointment.urls')),
    url(r'^test_results/', include('test_result.urls')),
    url(r'^message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [
    url(r'^inbox/$', views.InboxView.as_view(), name='inbox'),
    url(r'^outbox/$', views.OutboxView.as_view(), name='outbox'),
    url(r'^deleted/$', views.DeletedView.as_view(), name='deleted'),
    url(r'^new_message/$', views.MessageFormView.as_view(), name='newmessage'),
    url(r'^message/(?P<pk>[0-9]+)/$', views.MessageDetailView.as_view(), name='detail'),
    url(r'^remove/(?P<pk>[0-9]+)/$', views.RemoveMessageView.as_view(), name='remove'),
    url(r'^restore/(?P<pk>[0-9]+)/$', views.RestoreMessageView.as_view(), name='restore'),

]

patient_homepage/urls.py
from django.conf.urls import url
from patient_homepage import views

app_name = 'patient'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emr/$', views.viewemr, name='emr'),
    url(r'^emr/chronological/$', views.EMRChronView.as_view(), name='chronemr'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update1'),
    url(r'^profile/(?P<pk>[0-9]+)/update2/$', views.UpdatePatientInfo.as_view(), name='update2'),
    url(r'^addextrainfo/$', views.ExtraInfoFormView.as_view(), name='extra'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.DeleteEvent.as_view(), name='deleteevent'),
]

test_result/urls.py
from django.conf.urls import url
from test_result import views

app_name = 'test_result'

urlpatterns = [
    url(r'^addtestresult/(?P<pk>[0-9]+)/$', views.CreateTestResultView.as_view(), name='add'),
    url(r'^testfile/(?P<pk>[0-9]+)/$', views.FileView.as_view(), name='file'),
    url(r'^testfile/log/(?P<pk>[0-9]+)/$', views.LogFileView.as_view(), name='logfile'),
    url(r'^testresulthandler/(?P<pk>[0-9]+)/$', views.TestResultNotificationHandler.as_view(), name='notificationhandler'),
    url(r'^approvetestresulthandler/(?P<pk>[0-9]+)/$', views.ApproveTestResultNotificationHandler.as_view(), name='approvenotificationhandler'),
    url(r'^cancelapprovetestresult/(?P<pk>[0-9]+)/$', views.CancelApproveTestResultNotificationHandler.as_view(), name='cancelapprovetest'),
    url(r'^approvetestresult/(?P<pk>[0-9]+)/$', views.ApproveTestResult.as_view(), name='approvetestresult'),

]

accounts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.core.validators import RegexValidator


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('Staff Status'), default=False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    # avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def get_message_count(self):
        count = 0
        for message in self.receiver.all():
            if not message.deleted:
                count += 1
        return count

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.get_full_name() + " (" + self.email + ")"


class Hospital(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=16)  # validators should be a list

    def formatted_phone(self):
        return "%s%s%s-%s%s%s-%s%s%s%s" % tuple(self.phone_number)

    def __str__(self):
        return self.name


class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospital = models.ForeignKey(Hospital)

    def __str__(self):
        return "Nurse " + self.user.get_full_name() + " (" + self.user.email + ")"

    def get_doctors(self):
        return self.doctor_set.all()


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospitals = models.ManyToManyField(Hospital)
    max_patients = models.IntegerField()
    nurses = models.ManyToManyField(Nurse)

    def __str__(self):
        return "Dr. " + self.user.get_full_name() + " (" + self.user.email + ")"

    def get_hospitals(self):
        return self.hospitals.all()

    def get_nurses(self):
        return self.nurses.all()


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    insurance_number = models.CharField(max_length=13)
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    height = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    blood_type = models.CharField(max_length=10, blank=True)
    hospital = models.ForeignKey(Hospital)
    doctor = models.ForeignKey(Doctor)
    isInHospital = models.BooleanField(default=False)
    isInTransit = models.BooleanField(default=False)
    emergency_first_name = models.CharField(max_length=30, blank=True)
    emergency_last_name = models.CharField(max_length=30, blank=True)
    emergency_phone_number = models.CharField(blank=True, max_length=16)
    emergency_address = models.CharField(max_length=200, blank=True)
    emergency_relationship = models.CharField(max_length=50, blank=True)

    def get_absolute_url(self):
        return reverse('patient:profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.user.get_full_name() + " (" + self.user.email + ")"

    def get_filtered_events(self):
        return self.event_set.order_by('date').reverse()

    def no_basic_info(self):
        no = (not self.emergency_first_name) or (not self.phone_number) or (not self.address) \
             or (not self.emergency_last_name) or (not self.emergency_address) \
             or (not self.emergency_phone_number) or (not self.emergency_relationship)
        return no

    def get_unapproved_tests_number(self):
        all_tests = self.testresult_set.all()
        ans = 0
        for test in all_tests:
            if test.is_released:
                ans += 1
        return ans


class H_Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hospital = models.ForeignKey(Hospital)

    def __str__(self):
        return "Admin " + self.user.get_full_name() + " (" + self.user.email + ")"


class Notification(models.Model):
    name = models.CharField(max_length=100, blank=False)
    recipient = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    is_seen = models.BooleanField(default=False, blank=False)


class AppointmentNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    appointment = models.IntegerField()


class PrescriptionNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class RemovedPrescriptionNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class TestResultNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)


class ApproveTestResultNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    test_result = models.IntegerField()


class ReceiveTransferNotification(models.Model):
    notification = models.OneToOneField(Notification, on_delete=models.CASCADE)
    transfer = models.IntegerField()


class HospitalStay(models.Model):
    REASON_CHOICES = (
        ('Infectious Disease', 'Infectious Disease'),
        ('Traumatic Injury', 'Traumatic Injury'),
        ('Poisoning/Drugs', 'Poisoning/Drugs'),
        ('Cardiac Issues', 'Cardiac Issues'),
        ('Chronic Illness', 'Chronic Illness'),
        ('Surgery', 'Surgery'),
        ('Other', 'Other'),
    )

    patient = models.ForeignKey(Patient)
    hospital = models.ForeignKey(Hospital)
    admission_date = models.DateField()
    discharge_date = models.DateField(blank=True, null=True)
    reason = models.CharField(max_length=50, choices=REASON_CHOICES)
    admission_details = models.CharField(blank=True, max_length=256)
    discharge_details = models.CharField(blank=True, max_length=256)
    admit_employee = models.ForeignKey(User, related_name='admit_employee')
    discharge_employee = models.ForeignKey(User, related_name='discharge_employee', blank=True, null=True)

    def __str__(self):
        return self.patient.user.first_name + " " + self.patient.user.last_name +\
               " was admitted to " + self.hospital.name + " for: " + self.reason


class OngoingTransfer(models.Model):
    patient = models.ForeignKey(Patient)
    dest_doctor = models.ForeignKey(Doctor, related_name='dest_doctor')
    dest_hospital = models.ForeignKey(Hospital, related_name='dest_hospital')
    src_doctor = models.ForeignKey(Doctor, related_name='src_doctor')
    src_hospital = models.ForeignKey(Hospital, related_name='src_hospital')

patient_homepage/models.py
from django.db import models

# Create your models here.

patient_homepage/templates/patient_homepage/chronemr.html
{% extends 'accounts/base.html' %}

{% block title %}Electronic Medical Record{% endblock %}

{% block body %}

    <div class="center"><h3>{{ request.user.get_full_name }}'s Electronic Medical Record</h3></div>
    <div class="container" align="right">
        <a href="{% url 'patient:emr' %}">
            <button id="sortButton" class="btn btn-primary">Sorted View</button>
        </a>
        <a onclick="javascript:window.print()">
            <button id="print" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print" aria-hidden="true"></span></button>
        </a>
    </div>
    <!-- Medical Information -->
    <div class="container">
        <div class="panel panel-primary">

            <div class="panel-heading">
                <h4 class="panel-title">Medical Information</h4>
            </div>

            <div class="panel-body">
                <ul>
                    <li> Height:
                        {% if request.user.patient.height %}
                            {{ request.user.patient.height }}</li>
                        {% endif %}
                    <li> Weight:
                        {% if request.user.patient.weight %}
                            {{ request.user.patient.weight }}</li>
                        {% endif %}
                    <li> Blood Type: {{ request.user.patient.blood_type }}</li>
                </ul>
            </div>

        </div>
    </div>
    <!-- EMR -->
    {% if log_list.size == 0%}
        <div class="center"><h3>You have no medical records</h3></div>
    {% endif %}
    {% for log in log_list %}
    {% if log.presclog or log.admissionlog or log.type == "discharge" or log.testresultlog.is_released %}
    <div class="container">
        <div class="panel panel-primary">

            <div class="panel-heading">
            {% if log.presclog %}
                <h3 class="panel-title">Prescription</h3>
            {% elif log.admissionlog %}
                <h3 class="panel-title">Admission</h3>
            {% elif log.type == "discharge" %}
                <h3 class="panel-title">Discharge</h3>
            {% elif log.testresultlog %}
                <h3 class="panel-title">Test Result</h3>
            {% endif %}

            </div>

            <div class="panel-body">
                        {% if log.presclog %}
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2">Drug Name</th>
                                            <th class="col-md-2">Start Date</th>
                                            <th class="col-md-2">End Date</th>
                                            <th class="col-md-2">Number of refills</th>
                                            <th class="col-md-2">Dosage</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ log.presclog.drugname|truncatechars:32 }}</td>
                                            <td>{{ log.presclog.start_date }}</td>
                                            <td>{{ log.presclog.end_date }}</td>
                                            <td>{{ log.presclog.refills }}</td>
                                            <td>{{ log.presclog.dosage }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        {% elif log.admissionlog %}
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2">Hospital</th>
                                            <th class="col-md-2">Time</th>
                                            <th class="col-md-2">Reason</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ log.hospital.name }}</td>
                                            <td>{{ log.date_time }}</td>
                                            <td>{{ log.admissionlog.reason }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        {% elif log.type == "discharge" %}
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2">Hospital</th>
                                            <th class="col-md-2">Time</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ log.hospital.name }}</td>
                                            <td>{{ log.date_time }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        {% elif log.testresultlog %}
                            {% if log.testresultlog.is_released %}
                                <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="col-md-2">Name</th>
                                            <th class="col-md-2">Date</th>
                                            <th class="col-md-2">Information</th>
                                            <th class="col-md-2">File</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{ log.testresultlog.name }}</td>
                                            <td>{{ log.testresultlog.date }}</td>
                                            <td>{{ log.testresultlog.information }}</td>
                                            <td>{% if log.testresultlog.file %}
                                                    <a href="{% url 'test_result:logfile' log.pk %}">View Attached File</a>
                                                    {% endif %}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            {% endif %}
                        {% endif %}
            </div>

        </div>
    </div>
    {% endif %}
    {% endfor %}
{% endblock %}

patient_homepage/templates/patient_homepage/emr.html
{% extends 'accounts/base.html' %}

{% block title %} Electronic Medical Record {% endblock %}

{% block body %}
<div class="center"><h3>{{ request.user.get_full_name }}'s Electronic Medical Record</h3></div>

<div class="container" align="right">
    <a href="{% url 'patient:chronemr' %}">
        <button id="chronButton" class="btn btn-primary">Chronological View</button>
    </a>
    <a onclick="javascript:window.print()">
        <button id="print" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print" aria-hidden="true"></span></button>
    </a>
</div>
<!-- Medical Information -->
<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Medical Information</h4>
        </div>

        <div class="panel-body">
            <ul>
                <li> Height:
                    {% if request.user.patient.height %}
                        <var id="feet" style="font-style: normal"></var>ft <var id="inches" style="font-style: normal"></var>in</li>
                    {% endif %}
                    <script>
                        h = {{ request.user.patient.height }};
                        f = Math.trunc(h/12);
                        i = h % 12;
                        document.getElementById("inches").innerHTML = i.toString();
                        document.getElementById("feet").innerHTML = f.toString();
                    </script>
                <li> Weight:
                    {% if request.user.patient.weight %}
                        {{ request.user.patient.weight }}</li>
                    {% endif %}
                <li> Blood Type: {{ request.user.patient.blood_type }}</li>
            </ul>
        </div>

    </div>
</div>

    <!-- Prescriptions -->
<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Prescriptions</h4>
        </div>

        <div class="panel-body">
            <div class="table-responsive">
            {% if request.user.patient.prescription_set.all.count == 0 %}
                <div class="center"><h3>You have no prescriptions</h3></div>
            {% else %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="col-md-1">Drug Name</th>
                            <th class="col-md-3">Details</th>
                            <th class="col-md-1">Start Date</th>
                            <th class="col-md-1">End Date</th>
                            <th class="col-md-1">Number of refills</th>
                            <th class="col-md-1">Dosage</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for prescription in request.user.patient.prescription_set.all|dictsortreversed:"start_date" %}
                            <tr>
                                <td>{{ prescription.name }}</td>
                                <td>{{ prescription.information }}</td>
                                <td>{{ prescription.start_date }}</td>
                                <td>{{ prescription.end_date }}</td>
                                <td>{{ prescription.refills }}</td>
                                <td>{{ prescription.dosage }}{{ prescription.unit }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            </div>
        </div>

    </div>
</div>

    <!-- Test Results -->
<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Test Results</h4>
        </div>

        <div class="panel-body">
            {% if request.user.patient.get_unapproved_tests_number == 0 %}
                <div class="center"> <h3>You have no test results</h3></div>
            {% else %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="col-md-1">Name</th>
                            <th class="col-md-2">Information</th>
                            <th class="col-md-1">Date</th>
                            <th class="col-md-1">File</th>
                        </tr>
                    </thead>
                    <tr>
                        {% for testresult in request.user.patient.testresult_set.all|dictsortreversed:"date" %}
                            {% if testresult.is_released %}
                                <tr>
                                    <td>{{ testresult.name }}</td>
                                    <td>{{ testresult.information }}</td>
                                    <td>{{ testresult.date }}</td>
                                    <td>{% if testresult.file %}
                                        <a href="{% url 'test_result:file' testresult.pk %}"> View Attached File </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                </table>
            </div>
            {% endif %}
        </div>
    </div>
</div>


<!-- Hospital Stays -->
<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Previous Hospital Stays</h4>
        </div>

        <div class="panel-body">
            {% if request.user.patient.hospitalstay_set.all.count == 0 %}
                <div class="center"><h3>You have no hospital stays</h3></div>
            {% else %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Hospital</th>
                        <th>Date</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stay in request.user.patient.hospitalstay_set.all %}
                        <tr>
                            <td>{{ stay.hospital.name }}</td>
                            <td>{{ stay.admission_date }} - {% if stay.discharge_date %}{{ stay.discharge_date }}{%else%}Now{%endif%}</td>
                            <td>{{ stay.reason }}: {{ stay.admission_details }}<br>{{ stay.discharge_details }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

patient_homepage/templates/patient_homepage/profile.html
{% extends 'accounts/base.html' %}

{% block title %} Profile {% endblock %}

{% block body %}

{% if error_message %}
    <p style="color:red"><strong>{{ error_message }}</strong></p>
{% endif %}

<!-- Personal Information -->
<div class="container">
    <div class="center"><h3>Your Profile</h3></div>
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Personal Information</h4>
        </div>

        <div class="panel-body">
            <ul>
                <strong>First Name: </strong>{{ request.user.first_name }} <br>
                <strong>Last Name: </strong>{{ request.user.last_name }} <br>
                <strong>Date of Birth: </strong>{{ request.user.patient.date_of_birth }} <br>
                <strong>Email: </strong>{{ request.user.email }} <br>
                <strong>Address: </strong>{{ request.user.patient.address }} <br>
                <strong>Phone Number: </strong>{{ request.user.patient.phone_number }} <br>
                <strong>Insurance Number: </strong>{{ request.user.patient.insurance_number }} <br>
                <strong>Hospital: </strong>{{ request.user.patient.hospital }} <br>
                <strong>Doctor/PCP: </strong>{{ request.user.patient.doctor }} <br>
                <strong>Emergency Contact Information: </strong> <br>
                <ul>
                    First Name: {{ request.user.patient.emergency_first_name }} <br>
                    Last Name: {{ request.user.patient.emergency_last_name }} <br>
                    Phone Number: {{ request.user.patient.emergency_phone_number }} <br>
                    Address: {{ request.user.patient.emergency_address }} <br>
                    Relationship: {{ request.user.patient.emergency_relationship }} <br>
                </ul>
            </ul>



            <div class="col-md-12" style="text-align:right">
            <!-- Update Password -->
            <a href="{% url 'accounts:updatepassword'%}">
                    <button type="submit" class="btn btn-primary">Update Password</button>
            </a>
            <!-- Update Profile Information -->
                <a href="{% url 'patient:update1' request.user.pk %}">
                    <button type="submit" class="btn btn-success">Update Profile</button>
                </a>
            </div>
        </div>

    </div>

</div>


{% endblock %}