accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.PatientFormView.as_view(), name='register'),
    url(r'^register/step2/$', views.BasicInfo.as_view(), name='register2'),
    url(r'^admitpatient/$', views.AdmissionView.as_view(), name='admit'),
    url(r'^admitpatient/doctor$', views.AdmissionViewDoctor.as_view(), name='admitdoc'),
    url(r'^dischargepatient/$', views.DischargeView.as_view(), name='discharge'),
    url(r'^updatepassword/$', views.PasswordUpdateView.as_view(), name='updatepassword'),
    url(r'^transferpatient/$', views.TransferPatientView.as_view(), name='transfer'),
    url(r'^getdoctors/$', views.AjaxGetDoctorsView.as_view(), name='ajax_get_doctors'),
    url(r'^receivepatient/(?P<pk>[0-9]+)/$', views.ReceivePatientView.as_view(), name='transfernotificationhandler'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.patient_profile, name='patientprofile'),
    url(r'^updatemedicalinfo/(?P<pk>[0-9]+)/$', views.UpdateMedicalFormView.as_view(), name='updatemedicalinfo'),
    url(r'^help/$', views.HelpView.as_view(), name='help'),
    url(r'^locations/$', views.LocationsView.as_view(), name='locations'),
]

h_admin_homepage/urls.py
from django.conf.urls import url
from h_admin_homepage import views

app_name = 'h_admin'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
    url(r'^register-staff/$', views.CreateUserFormView.as_view(), name='addstaff'),
    url(r'^register-staff/add-doctor-step1/$', views.CreateDoctorFormView.as_view(), name='register_doctor1'),
    url(r'^register-staff/add-doctor-step2/$', views.CreateDoctor2FormView.as_view(), name='register_doctor2'),
    url(r'^register-staff/add-nurse-step1/$', views.CreateNurseFormView.as_view(), name='register_nurse'),
    url(r'^register-staff/add-nurse-step2/$', views.CreateNurse2FormView.as_view(), name='register_nurse2'),
    url(r'^register-staff/add-hospital-admin/$', views.CreateAdminFormView.as_view(), name='register_admin'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),
    url(r'^statistics/$', views.StatsView.as_view(), name='statistics'),
    url(r'^upload-csv-file/$', views.UploadCsvFile.as_view(), name='upload_csv_file'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.DeleteEvent.as_view(), name='deleteevent'),
]

healthnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from healthnet import views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage_redirect, name='homepage_redirect'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^h_admin_homepage/', include('h_admin_homepage.urls')),
    url(r'^doctor_homepage/', include('doctor_homepage.urls')),
    url(r'^patient_homepage/', include('patient_homepage.urls')),
    url(r'^nurse_homepage/', include('nurse_homepage.urls')),
    url(r'^prescriptions/', include('prescription.urls')),
    url(r'^appointments/', include('appointment.urls')),
    url(r'^test_results/', include('test_result.urls')),
    url(r'^message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [
    url(r'^inbox/$', views.InboxView.as_view(), name='inbox'),
    url(r'^outbox/$', views.OutboxView.as_view(), name='outbox'),
    url(r'^deleted/$', views.DeletedView.as_view(), name='deleted'),
    url(r'^new_message/$', views.MessageFormView.as_view(), name='newmessage'),
    url(r'^message/(?P<pk>[0-9]+)/$', views.MessageDetailView.as_view(), name='detail'),
    url(r'^remove/(?P<pk>[0-9]+)/$', views.RemoveMessageView.as_view(), name='remove'),
    url(r'^restore/(?P<pk>[0-9]+)/$', views.RestoreMessageView.as_view(), name='restore'),

]

nurse_homepage/urls.py
from django.conf.urls import url
from nurse_homepage import views

app_name = 'nurse'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^emr/$', views.EMRView.as_view(), name='emr'),
    url(r'^emr/(?P<pk>[0-9]+)/$', views.EMRPatientView.as_view(), name='patientemr'),
    url(r'^emr/(?P<pk>[0-9]+)/chronological/$', views.viewchronemr, name='chronemr'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.profile_view, name='profile'),
    url(r'^profile/(?P<pk>[0-9]+)/update/$', views.UpdateUserInfo.as_view(), name='update'),
]

prescription/urls.py
from django.conf.urls import url
from . import views

app_name = 'prescription'

urlpatterns = [
    url(r'^addprescription/(?P<pk>[0-9]+)/$', views.CreatePrescriptionView.as_view(), name='add'),
    url(r'^removeprescription/(?P<pk>[0-9]+)/$', views.RemovePrescriptionView.as_view(), name='remove'),
    url(r'^notificationhandler/(?P<pk>[0-9]+)/$', views.PrescriptionNotificationHandler.as_view(), name='notificationhandler'),
]

test_result/urls.py
from django.conf.urls import url
from test_result import views

app_name = 'test_result'

urlpatterns = [
    url(r'^addtestresult/(?P<pk>[0-9]+)/$', views.CreateTestResultView.as_view(), name='add'),
    url(r'^testfile/(?P<pk>[0-9]+)/$', views.FileView.as_view(), name='file'),
    url(r'^testfile/log/(?P<pk>[0-9]+)/$', views.LogFileView.as_view(), name='logfile'),
    url(r'^testresulthandler/(?P<pk>[0-9]+)/$', views.TestResultNotificationHandler.as_view(), name='notificationhandler'),
    url(r'^approvetestresulthandler/(?P<pk>[0-9]+)/$', views.ApproveTestResultNotificationHandler.as_view(), name='approvenotificationhandler'),
    url(r'^cancelapprovetestresult/(?P<pk>[0-9]+)/$', views.CancelApproveTestResultNotificationHandler.as_view(), name='cancelapprovetest'),
    url(r'^approvetestresult/(?P<pk>[0-9]+)/$', views.ApproveTestResult.as_view(), name='approvetestresult'),

]

h_admin_homepage/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View, ListView, UpdateView, DeleteView
from appointment.models import Event
from appointment.forms import EventForm
import datetime
from django.utils import timezone
import calendar
from django.template.context_processors import csrf
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from .forms import *
from io import TextIOWrapper
from prescription.models import Prescription
from collections import OrderedDict
from healthnet.views import load_csv
from log.models import *
from django.db.models import Q


def index(request):
    request.session['dash'] = 1
    request.session['emr'] = None
    request.session['profile'] = None
    request.session['messages'] = None

    request.session['name'] = None
    request.session['date'] = None
    request.session['start_time'] = None
    request.session['patient'] = None
    request.session['doctor'] = None

    request.session['email'] = None
    request.session['first_name'] = None
    request.session['last_name'] = None
    request.session['password'] = None
    request.session['usertype'] = None
    request.session['hospitals'] = None
    request.session['max_patients'] = None
    request.session['nurses'] = None
    request.session['hospital'] = None
    request.session['doctors'] = None

    new_event_form = EventForm()
    now = datetime.date.today()
    year = now.year
    month = now.month
    cal = calendar.Calendar(calendar.SUNDAY)
    month_days = cal.monthdatescalendar(year, month)

    events = []
    times = [datetime.time(9, 00),
             datetime.time(9, 30),
             datetime.time(10, 00),
             datetime.time(10, 30),
             datetime.time(11, 00),
             datetime.time(11, 30),
             datetime.time(12, 00),
             datetime.time(12, 30),
             datetime.time(13, 00),
             datetime.time(13, 30),
             datetime.time(14, 00),
             datetime.time(14, 30),
             datetime.time(15, 00),
             datetime.time(15, 30),
             datetime.time(16, 00),
             datetime.time(16, 30),
             datetime.time(17, 00)]
    if request.method == 'GET':
        for week in month_days:
            if now in week:
                weekly_events = []
                for day in week:
                    if day == now:
                        weekly_events.append((day, []))
                events.append(weekly_events)
        args = {'events': events, 'month': month, 'year': year, 'date': now, 'month_days': month_days}
        args.update(csrf(request))
        args['new_event_form'] = new_event_form
        args['calendar_view'] = 'Daily'
        args['doctors'] = request.user.h_admin.hospital.doctor_set.all()
        args['patients'] = Patient.objects.filter(hospital=request.user.h_admin.hospital)
        args['times'] = times
        return render(request, 'h_admin_homepage/h_admin_homepage.html', args)
    elif request.method == 'POST':
        if not request.POST['calendar_view']:
            calendar_view = 'Daily'
        else:
            calendar_view = request.POST['calendar_view']

        if request.POST['dob_month']:
            month = int(request.POST['dob_month'])
        if request.POST['dob_year']:
            year = int(request.POST['dob_year'])
        if request.POST['dob_day']:
            day = int(request.POST['dob_day'])
            chosen_day = day
        else:
            chosen_day = now.day

        try:
            chosen_day = datetime.date(year, month, chosen_day)
        except ValueError:
            for week in month_days:
                if now in week:
                    weekly_events = []
                    for day in week:
                        if day == now:
                            weekly_events.append((day, []))
                    events.append(weekly_events)
            args = {'events': events, 'month': month, 'year': year, 'date': now, 'month_days': month_days}
            args.update(csrf(request))
            args['new_event_form'] = new_event_form
            args['calendar_view'] = 'Daily'
            args['doctors'] = request.user.h_admin.hospital.doctor_set.all()
            args['patients'] = Patient.objects.filter(hospital=request.user.h_admin.hospital)
            args['times'] = times
            return render(request, 'h_admin_homepage/h_admin_homepage.html', args)

        month_days = cal.monthdatescalendar(year, month)

        chosen_doctor = None
        chosen_patient = None
        if request.POST['chosen_doctor']:
            chosen_doctor = Doctor.objects.get(pk=request.POST['chosen_doctor'])
        if request.POST['chosen_patient']:
            chosen_patient = Patient.objects.get(pk=request.POST['chosen_patient'])

        if (not chosen_doctor and not chosen_patient) or (chosen_doctor and chosen_patient):
            if calendar_view == 'Monthly':
                for week in month_days:
                    weekly_events = []
                    for day in week:
                        weekly_events.append((day, []))
                    events.append(weekly_events)
            elif calendar_view == 'Weekly':
                for week in month_days:
                    if chosen_day in week:
                        weekly_events = []
                        for day in week:
                            weekly_events.append((day, []))
                        events.append(weekly_events)
            elif calendar_view == 'Daily':
                for week in month_days:
                    weekly_events = []
                    for day in week:
                        if chosen_day == day:
                            weekly_events.append((day, []))
                    events.append(weekly_events)

        if chosen_doctor and not chosen_patient:
            if calendar_view == 'Monthly':
                for week in month_days:
                    weekly_events = []
                    for day in week:
                        events_for_one_day = []
                        events_for_doctor = Event.objects.filter(doctor=chosen_doctor, date=day).order_by('start_time')
                        for event in events_for_doctor:
                            if event.patient:
                                # if event.patient.hospital == request.user.h_admin.hospital:
                                    events_for_one_day.append(event)
                        weekly_events.append((day, events_for_one_day))
                    events.append(weekly_events)
            elif calendar_view == 'Weekly':
                for week in month_days:
                    if chosen_day in week:
                        weekly_events = []
                        for day in week:
                            events_for_one_day = []
                            events_for_doctor = Event.objects.filter(doctor=chosen_doctor, date=day).order_by('start_time')
                            for event in events_for_doctor:
                                if event.patient:
                                    # if event.patient.hospital == request.user.h_admin.hospital:
                                        events_for_one_day.append(event)
                            weekly_events.append((day, events_for_one_day))
                        events.append(weekly_events)
            elif calendar_view == 'Daily':
                for week in month_days:
                    weekly_events = []
                    for day in week:
                        if day == chosen_day:
                            events_for_one_day = []
                            events_for_doctor = Event.objects.filter(doctor=chosen_doctor, date=day).order_by('start_time')
                            for event in events_for_doctor:
                                if event.patient:
                                    # if event.patient.hospital == request.user.h_admin.hospital:
                                        events_for_one_day.append(event)
                            weekly_events.append((day, events_for_one_day))
                    events.append(weekly_events)

        if chosen_patient and not chosen_doctor:
            if calendar_view == 'Monthly':
                for week in month_days:
                    week_events = [
                        (day, Event.objects.filter(patient=chosen_patient, date=day).order_by('start_time')) for
                        day in week]
                    events.append(week_events)
            elif calendar_view == 'Weekly':
                for week in month_days:
                    if chosen_day in week:
                        week_events = [
                            (day, Event.objects.filter(patient=chosen_patient, date=day).order_by('start_time'))
                            for day in week]
                        events.append(week_events)
            elif calendar_view == 'Daily':
                for week in month_days:
                    for day in week:
                        if day == chosen_day:
                            week_events = [(day, Event.objects.filter(patient=chosen_patient, date=day).order_by(
                                'start_time'))]
                            events.append(week_events)

        args = {'events': events, 'month': month, 'year': year, 'date': chosen_day, 'month_days': month_days}
        args.update(csrf(request))
        args['new_event_form'] = new_event_form
        args['calendar_view'] = calendar_view
        args['doctors'] = request.user.h_admin.hospital.doctor_set.all()
        args['patients'] = Patient.objects.filter(hospital=request.user.h_admin.hospital)
        args['times'] = times
        if chosen_patient and not chosen_doctor:
            args['chosen_patient'] = chosen_patient
            if calendar_view == 'Daily':
                doctor_events = Event.objects.filter(doctor=chosen_patient.doctor, date=chosen_day).exclude(

h_admin_homepage/templates/h_admin_homepage/admin_registration_form.html
{% extends 'accounts/base.html' %}
{% block title %}Add A Hospital Admin{% endblock %}
{% block body %}
    <div class="center"><h3>Create a Hospital Admin Account</h3></div>
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7  center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                    <a href="{% url 'h_admin:addstaff' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>

                                <div class="col-md-6" style="text-align:right">
                                    <a href="{% url 'h_admin:index' %}">
                                        <button type="button" class="btn btn-danger">Cancel</button>
                                    </a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

h_admin_homepage/templates/h_admin_homepage/doctor_registration_form1.html
{% extends 'accounts/base.html' %}
{% block title %}Add A Doctor{% endblock %}
{% block body %}
    <div class="center"><h3>Create a Doctor Account</h3></div>
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7  center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                    <a href="{% url 'h_admin:addstaff' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>

                                <div class="col-md-6" style="text-align:right">
                                    <a href="{% url 'h_admin:index' %}">
                                        <button type="button" class="btn btn-danger">Cancel</button>
                                    </a>
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

h_admin_homepage/templates/h_admin_homepage/doctor_registration_form2.html
{% extends 'accounts/base.html' %}
{% block title %}Add A Doctor{% endblock %}
{% block body %}
    <div class="center"><h3>Create a Doctor Account (Cont.)</h3></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7  center-block " style="float:none;">
                <div class="panel panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <div class="col-sm-offset-4 col-sm-8">
                                <p style="color:red"><strong>{{ error_message }}</strong></p>
                            </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post">
                            {% csrf_token %}
                            {% include 'accounts/form_template.html' %}
                            <div class="form-group">
                                <div class="col-md-6" style="text-align:left">
                                    <a href="{% url 'h_admin:register_doctor1' %}">
                                        <button type="button" class="btn btn-primary">Go Back</button>
                                    </a>
                                </div>
                                <div class="col-md-6" style="text-align:right">
                                <a href="{% url 'h_admin:index' %}">
                                        <button type="button" class="btn btn-danger">Cancel</button>
                                </a>
                                    &nbsp;<button type="submit" class="btn btn-success">Submit</button>
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

h_admin_homepage/templates/h_admin_homepage/emr.html
{% extends 'doctor_homepage/emr.html' %}

h_admin_homepage/templates/h_admin_homepage/patientemr.html
{% extends 'accounts/base.html' %}
{% block title %}{{ patient.user.get_full_name }}'s EMR{% endblock %}

{% block body %}

<div class="center">
    <h3>{{ patient.user.get_full_name }}'s Electronic Medical Record</h3>
</div>

<div class="container" align="right">
    {% if request.user.doctor %}
        <a href="{% url 'doctor:chronemr' patient.pk %}">
    {% elif request.user.h_admin %}
        <a href="{% url 'h_admin:chronemr' patient.pk %}">
    {% elif request.user.nurse %}
        <a href="{% url 'nurse:chronemr' patient.pk %}">
    {% endif %}
        <button id="chronButton" type="button" class="btn btn-primary">Chronological View</button>
    </a>
    <a onclick="javascript:window.print()">
        <button id="print" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print" aria-hidden="true"></span></button>
    </a>
</div>

<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Medical Information</h4>
        </div>

        <div class="panel-body">
            <a href="{% url 'accounts:updatemedicalinfo' patient.pk %}">
                <button id="updateButton" type="submit" class="btn btn-success">Update Medical Information</button>
            </a>
            <ul>

                <li> Height:
                    {% if patient.height %}
                        <var id="feet" style="font-style: normal"></var>ft <var id="inches" style="font-style: normal"></var>in</li>
                    {% endif %}
                    <script>
                        h = {{ patient.height }};
                        f = Math.trunc(h/12);
                        i = h % 12;
                        document.getElementById("inches").innerHTML = i.toString();
                        document.getElementById("feet").innerHTML = f.toString();
                    </script>
                <li> Weight:
                    {% if patient.weight %}
                        {{ patient.weight }}</li>
                    {% endif %}
                <li> Blood Type: {{ patient.blood_type }}</li>
            </ul>
        </div>

    </div>
</div>


    <!-- Prescriptions -->
<div class="container">
<div class="panel panel-primary">

    <div class="panel-heading">
        <h4 class="panel-title">Prescriptions</h4>
    </div>

    <div class="panel-body">
        <a href="{% url 'prescription:add' patient.pk %}">
            <button id="addPrescButton" type="submit" class="btn btn-success">Add a Prescription</button>
        </a>
        <div class="table-responsive">
            {% if patient.prescription_set.all.count == 0 %}
                <center><h3>{{ patient.user.first_name }} has no prescriptions</h3></center>
            {% else %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="col-md-1">Drug Name</th>
                            <th class="col-md-3">Details</th>
                            <th class="col-md-1">Start Date</th>
                            <th class="col-md-1">End Date</th>
                            <th class="col-md-1">Number of refills</th>
                            <th class="col-md-1">Dosage</th>
                            <th class="col-md-1">Remove Prescription</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for prescription in patient.prescription_set.all|dictsortreversed:"start_date" %}
                            <tr>
                                <td>{{ prescription.name|truncatechars:32 }}</td>
                                <td>{{ prescription.information }}</td>
                                <td>{{ prescription.start_date }}</td>
                                <td>{{ prescription.end_date }}</td>
                                <td>{{ prescription.refills }}</td>
                                <td>{{ prescription.dosage }}{{ prescription.unit }}</td>
                                <td>{% if not prescription.removed %}
                                    <a href="{% url 'prescription:remove' prescription.pk%}">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                {% endif %}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>

</div>
</div>

    <!-- Test Results -->
<div class="container">
<div class="panel panel-primary">

    <div class="panel-heading">
        <h4 class="panel-title">Test Results</h4>
    </div>

    <div class="panel-body">
        <a href="{% url 'test_result:add' patient.pk %}">
            <button id="addResultButton" type="submit" class="btn btn-success">Add Test Result</button>
        </a>
        <div class="table-responsive">
            {% if patient.testresult_set.all.count == 0 %}
                <center><h3>{{ patient.user.first_name }} has no test results</h3></center>
            {% else %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="col-md-1">Test Result Name</th>
                            <th class="col-md-2">Information</th>
                            <th class="col-md-1">Date</th>
                            <th class="col-md-1">File</th>
                            <th class="col-md-1">Approved</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for testresult in patient.testresult_set.all|dictsortreversed:"date" %}
                            <tr>
                                <td>{{ testresult.name }}</td>
                                <td>{{ testresult.information }}</td>
                                <td>{{ testresult.date }}</td>
                                <td>{% if testresult.file %}
                                    <a href="{% url 'test_result:file' testresult.pk %}">View Attached File
                                    </a>
                                    {% endif %}
                                </td>
                                <td> {% if testresult.is_released %}
                                    Approved
                                    {% else %}
                                        <a href="{% url 'test_result:approvetestresult' testresult.pk %}">Unapproved</a>
                                    {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>

</div>
</div>


<!-- Hospital Stays -->
<div class="container">
    <div class="panel panel-primary">

        <div class="panel-heading">
            <h4 class="panel-title">Previous Hospital Stays</h4>
        </div>

        <div class="panel-body">
            {% if patient.hospitalstay_set.all.count == 0 %}
                <center><h3>{{ patient.user.first_name }} has no hospital stays</h3></center>
            {% else %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Hospital</th>
                        <th>Date</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stay in patient.hospitalstay_set.all|dictsortreversed:"admission_date" %}
                        <tr>
                            <td>{{ stay.hospital.name }}</td>
                            <td>{{ stay.admission_date }} - {% if stay.discharge_date %}{{ stay.discharge_date }}{%else%}Now{%endif%}</td>
                            <td>{{ stay.reason }}: {{ stay.admission_details }}<br>{{ stay.discharge_details }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}